### ISSUE TITLE
This needs a syntax migration

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/popt-feedstock#3]

**Comment by CJ-Wright** [comment]
Ping @conda-forge/popt

**Comment by CJ-Wright** [comment]
(The bot seems to not be able to do this, so you might need to do it by hand)

**Comment by sodre** [comment]
and... it happens to be me :)

**Comment by CJ-Wright** [comment]
Sorry, I would do it myself but I've got some major releases scheduled for next week.

**Comment by sodre** [comment]
no big deal, it was just that I had no idea I had also created the popt package. I'll get to it later tonight.

**Comment by sodre** [comment]
Closed in #4
